config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  devise_for :users, path: "users", controllers: { registrations: "registrations"},
    path_names: { sign_in: "login", sign_up: "register" }
  authenticate :user, ->(u) { u.admin? } do
    resources :secret_codes
    root "secret_codes#index"
  end
  authenticate :user, ->(u) { u.user? } do
    root "home#index"
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == "admin"
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  require "securerandom"
  NUM_OF_CODES = %w[1 10 20 50 100]

  belongs_to :user, optional: true

  before_save :save_secret_code

  def save_secret_code
    self.code = generate_secret_hash
  end

  private

  def generate_secret_hash
    SecureRandom.hex(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :secret_code

  enum role: [:user, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create
    build_resource(sign_up_params.merge(role: User.roles[:user]))
    yield resource if block_given?
    @secret_code = SecretCode.find_by(code: params[:secret_key])
    if @secret_code.present?
      if @user.save
        @secret_code.update_column("user_id", @user.id)
        respond_to do |format|
          format.html do
            redirect_to new_user_session_path
          end
        end
      end
    else
      flash[:alert] = resource.errors.full_messages.to_sentence
      render 'new'
    end
  end

  protected

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :current_password,
                                 :password_confirmation, :secret_key, :role)
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  load_and_authorize_resource
  def index
    @secret_codes = SecretCode.all
  end

  def new
    @secret_code = SecretCode.new
  end

  def create
    params[:num_of_code].to_i.times do |secret_code|
      @secret_code = SecretCode.new
      @secret_code.save
    end
    redirect_to secret_codes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/home/index.html.erb
<h1>Hi <%= current_user.email %>, Welcome to EngineerAIApp</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnginnerAIRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% if current_user %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/secret_codes/index.html.erb
<h2>Secret Codes</h2>
<%= button_to "Generate More Secret Code", new_secret_code_path, method: :get %>
<% if @secret_codes.present? %>
  <table>
    <tr>
      <td>
        <th>Code</th>
      </td>
      <td>
        <th>User Email</th>
      </td>
    </tr>
    <% @secret_codes.each do |secret_code| %>
      <tr>
        <td>
          <%= secret_code.code %>
        </td>
        <td>
          <%= secret_code&.user&.email %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/secret_codes/new.html.erb
<%= form_for(@secret_code) do |f| %>
  <%= label_tag :num_of_code, "How many codes you want to generate" %>
  <%= select_tag :num_of_code, options_for_select(SecretCode::NUM_OF_CODES, 10) %>
  <%= f.submit "Submit" %>
<% end %>